Controllers films users
mvinogradovHub/java-filmorate pull request #3
Opened 2023-02-15 08:13 UTC by mvinogradovHub

Не понятно как делать тесты на поля, у которых проверка идет аннотациями. Сделал тесты только на те проверки, которые сделал сам.

2023-02-15 17:26 UTC, TomattmanYandex requested changes
Привет хорошо, стоит немного переделать, и есть переусложения, лучше не перебарщивать с этим, чтобы проблем потом не возникло

2023-02-15 17:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/Exception/ErrorResponse.java
> +public class ErrorResponse {
спринг сам умеет оборачивать исключения в сообщения ответа, этот класс не нужен

2023-02-15 17:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/Exception/FilmorateAdvice.java
> +public class FilmorateAdvice {
и снова, спринг сам с этим достаточно хорошо справляется, на текущем уровне это точно не надо было, достаточно было просто пробросить ошибку валидации

2023-02-15 17:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/Exception/NotFoundException.java
> +public class NotFoundException extends Exception{
да и этот класс не особо нужен

2023-02-15 17:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/Exception/ValidationException.java
> +public class ValidationException extends Exception{
а этот лучше унаследовать от RuntimeException

2023-02-15 17:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!films.containsKey(film.getId())) {
обычно при добавлении мы не проверяем такое, чаще всего просто устанавливаем новый id и сохраняем

2023-02-15 17:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
лучше использовать обертку вместо примитива

2023-02-15 17:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/utils/UtilsUser.java
> +    public static User WriteUserNameFromLogin(User user) {
методы именуем с маленькой буквы

2023-02-15 17:26 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/utils/Validate.java
> +    public static void AdditionalValidateFilm(Film film) throws ValidationException {
методы с маленькой буквы

2023-02-15 17:26 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void validateFilm() {
лучше сделать несколько тестов с разными проверками, а не проверять все в одном методе

2023-02-16 15:13 UTC, TomattmanYandex approved these changes
Все хорошо, так мелкие пожелания которые можно к следующему спринту поправить

2023-02-16 15:13 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/utils/Validate.java
> +public class Validate {
Лучше переименовать в Validator

2023-02-16 15:13 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/utils/Validate.java
> +public class Validate {
А еще лучше в FIlmValidator

2023-02-17 08:39 UTC, mvinogradovHub commented on src/main/java/ru/yandex/practicum/filmorate/utils/Validate.java
> +public class Validate {
OK

2023-02-17 09:08 UTC, TomattmanYandex approved these changes
+

2023-02-17 10:25 UTC, merged