feature add database
mvinogradovHub/java-filmorate pull request #5
Opened 2023-03-29 14:18 UTC by mvinogradovHub

2023-03-29 16:05 UTC, mvinogradovHub commented
Что-то не работают тесты и не получается это исправить

2023-03-29 17:24 UTC, mvinogradovHub commented
ура

2023-03-30 08:15 UTC, TomattmanYandex requested changes
Привет, не хватает картинки со схемой базы и заполненого файла readme.md
В целом работа отличная, но есть моменты которые следует переделать

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +INSERT INTO MPA (MPA_ID, NAME) VALUES (1,'G');
Возможно было бы удобнее использовать два отдельных файла, один для структуры бд, другой для данных

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +	FILM_GENRE_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
для связывающих таблиц id не нужен, мы эти данные отдельно никак не используем, поэтому и это поле так же не нужно

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        Mpa receivedMpa = mpaStorage.getMpaById(id);
еще вариант как это можно использовать  - чтобы хранилище возвращало optional

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/db/FilmDbStorage.java
> +    private Long getNewFilmId() {
Интересный способ, обычно конечно используется встроенный генератор но тоже неплохой вариант

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/db/FilmDbStorage.java
> +        String sqlSelectFilm = "SELECT * FROM FILM";
полученный фильм не будет содержать ни рейтинга ни жанров

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/db/FilmDbStorage.java
> +        String sqlSelectFilm = "SELECT * FROM FILM WHERE FILM_ID = ?";
тут то же самое

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/db/UserDbStorage.java
> +        UtilsUser.writeUserNameFromLogin(user);
это логика сервиса а не хранилища

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/db/UserDbStorage.java
> +        if (users.isEmpty()) {
можно возвращать List<User> и не делать этих всех превращений

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/db/UserDbStorage.java
> +                "\tg.USER_ID,\n" +
с этим форматированием запрос просто нечитаемый

2023-03-30 08:15 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/db/UserDbStorage.java
> +        return getFriends(userId).stream().filter(getFriends(otherId)::contains).collect(Collectors.toSet());
хороший способ, простой и надежный, приму и так, но было бы прикольно попробовать все сделать запросом SQL

2023-03-30 08:15 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    private final UserDbStorage userStorage;
это тест какого класса, сервиса, компонента, обычно тестирование разных компонентов в разных файлах, стоит разделить

2023-03-30 09:15 UTC, mvinogradovHub commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        Mpa receivedMpa = mpaStorage.getMpaById(id);
Я думал над этим, но ведь тогда нам бы пришлось переделать сервис чтобы он принимал optional из хранилища, а вследствие этого надо переделать хранилище работы из памяти т.к. оно также не работает с optional. Это конечно не относится к mpa, но к другим объектам, которые уже были реализованы в рамках работы с памятью. Это как рекомендация или всеже нужно все переделать на optional?

2023-03-30 09:16 UTC, mvinogradovHub commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/db/FilmDbStorage.java
> +    private Long getNewFilmId() {
Подскажите, как использовать встроенный генератор или где об этом почитать? В теории об этом ни слова, поэтому использовал те инструменты, которые были.

2023-03-30 09:18 UTC, mvinogradovHub commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/db/FilmDbStorage.java
> +        String sqlSelectFilm = "SELECT * FROM FILM";
Будет содеражть, посмотрите пожалуйста метод создания фильма. Он использует другие методы хранилища чтобы собрать фильм
![image](https://user-images.githubusercontent.com/114647156/228789952-0a118f84-7cf3-4079-9e85-2f88b688042e.png)

2023-03-30 09:20 UTC, mvinogradovHub commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/db/UserDbStorage.java
> +        if (users.isEmpty()) {
Как и с optional. Тогда по цепочек придется переделывать то что было сделано при работе с памятью. Честно я уже не помню зачем там был нужен именно этот тип и что будет если я поменяю. Это рекомендация или нужно переделать?

2023-03-30 09:20 UTC, mvinogradovHub commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/db/UserDbStorage.java
> +        return getFriends(userId).stream().filter(getFriends(otherId)::contains).collect(Collectors.toSet());
попробую

2023-03-30 09:21 UTC, mvinogradovHub commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    private final UserDbStorage userStorage;
переделаю

2023-03-30 09:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        Mpa receivedMpa = mpaStorage.getMpaById(id);
это рекомендация

2023-03-30 09:56 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/db/FilmDbStorage.java
> +    private Long getNewFilmId() {
sequences sql гуглить это

2023-03-30 10:04 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/db/FilmDbStorage.java
> +        String sqlSelectFilm = "SELECT * FROM FILM";
тогда два момента, не надо смешивать логику сборки обьекта из резалт сета и новые запросы, ибо такое поддерживать будет тяжело
второй, для каждого фильма будет отдельный запрос на получение списка жанров, это тоже не правильно, представь что хочешь получить все фильмы, а их там 1000 это получиться 3001 запрос в базу, хотя можно сделать в два (можно даже в 1 но гораздо проще в два)

2023-03-30 10:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/db/UserDbStorage.java
> +        if (users.isEmpty()) {
это тоже на уровне рекомендации

2023-04-01 09:04 UTC, TomattmanYandex approved these changes
Привет, отлично, принято

2023-04-01 09:04 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/storage/film/impl/db/FilmDbStorageTest.java
> +    public void getFilmById_FilmMustHaveTheName_2012() {
Такие тесты не имеют особо смысла, лучше уже проверить весь возвращаемый обьект, что все поля вернулись как надо
так мы проверяемв весь метод,, 
так же и предыдущий метод, можно проверит что в базе создалась полностью соответствующий обьеке

2023-04-10 19:00 UTC, merged